name: Deploy Development Environment

on:
  push:
    branches:
      - development
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Checkout development branch
        uses: actions/checkout@v3
        with:
          ref: development

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Checkout gh-pages-dev branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages-dev
          clean: false

      - name: Copy build files
        run: |
          mkdir -p dist
          cp -r dist/* dist/

      - name: Commit and push to gh-pages-dev
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add dist/
          git commit -m "chore: Deploy development build" || echo "No changes to commit"
          git push origin gh-pages-dev
